### ISSUE TITLE
Can't get this to work, could you provide more instructions.

### ISSUE THREAD

**Issue by kevincam3** [ui-jar/ui-jar#10]
Here's the error I'm getting.
![image](https://user-images.githubusercontent.com/870934/34140516-5d82b486-e462-11e7-9c82-3dc42359dea5.png)

**Comment by nording** [comment]
Thanks for feedback!
Have you added "GameControlComponent" to any @NgModule in your app? And added "GameControlComponent" to the "exports" property in that @NgModule ? 

Also do you have a test for your "GameControlComponent"?

**Comment by saulide** [comment]
Had same problem, adding to the exports helped to overcome it

**Comment by kevincam3** [comment]
@nording, thanks for the input. So I only have one module in app.module.ts where I've added it 
![image](https://user-images.githubusercontent.com/870934/34153500-7311080c-e499-11e7-8f3a-2c65e674faa1.png)

Do I need to change my code so that every component has its own module for it to work?

I have not created any test yet. So it sounds like that must be done as well, is that correct?

**Comment by nording** [comment]
Allright I see! 
No, you don't have to put each component in it's own module.
With your current setup you should only have to add a test to your "GameControlComponent", https://github.com/ui-jar/ui-jar/blob/master/README.md#test-code

Let me know if it doesn't work.
I will make sure to clarify the error messages!

**Comment by kevincam3** [comment]
@nording,

Thanks for that help, I think I'm at the final stretch. It's now at least generating the screen. It's missing the actual button html that's in the *.component.html file Here's the error I'm getting now:

![image](https://user-images.githubusercontent.com/870934/34205769-e4f9c306-e56a-11e7-8d8f-9614d38d3c08.png)

Here's what the screen looks like that it's generating.

![image](https://user-images.githubusercontent.com/870934/34205784-f58ccd30-e56a-11e7-8e4b-b1da2a1af5e9.png)

Thanks again for all your help.

**Comment by nording** [comment]
Allright, how does the other "tsconfig.json" that you extend your "tsconfig.app.json" look like?

**Comment by kevincam3** [comment]
@nording,

Here it is:
![image](https://user-images.githubusercontent.com/870934/34211407-1dd6ea72-e580-11e7-99d4-ff0cef78967f.png)

**Comment by nording** [comment]
@kevincam3 I ment the "tsconfig.json" that is located in the root folder "cmp-databinding-start" :)

**Comment by kevincam3** [comment]
@nording ok here it is:

![image](https://user-images.githubusercontent.com/870934/34213250-cb14b8a4-e585-11e7-8a9a-5d5ca1de616a.png)

**Comment by nording** [comment]
Okey, are you using Angular CLI 1.5 ? 
Check out this comment, https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325
Based on the error message it sounds like you might need to add the following in your "tsconfig.app.json".

` 
...
"include": [
    "../src/**/*.ts"
]
...,`

**Comment by kevincam3** [comment]
I'm using Angular CLI 1.6
The site loads okay just running ng serve.
I added what you suggested and now there are new errors with the Typescript
![image](https://user-images.githubusercontent.com/870934/34219727-3ec9cc4a-e599-11e7-93c5-b44122d1b7dc.png)

**Comment by nording** [comment]
Hm, does it work if you add the following to the same "tsconfig.app.json"?.

```
...
"exclude": [
    "test.ts",
    "**/*.spec.ts",
    "../src/**/*.spec.ts"
]
...
```

**Comment by kevincam3** [comment]
Still a no go:
![image](https://user-images.githubusercontent.com/870934/34220122-945b7978-e59a-11e7-8a0f-e2b633114089.png)

**Comment by nording** [comment]
Okey, could you provide your .angular-cli.json that is located in your root folder? I would like to check if it has the correct setup.

**Comment by kevincam3** [comment]
Ok, here it is:
[angular-cli.zip](https://github.com/ui-jar/ui-jar/files/1576493/angular-cli.zip)

**Comment by nording** [comment]
It looks correct, I will give it a try with Angular CLI 1.6, to see if I can reproduce it and hopefully give you a correct answer :)

**Comment by kevincam3** [comment]
Ok, thanks.

**Comment by nording** [comment]
Allright I could reproduce it.
This fixed the issue for me, also add this to the same "tsconfig.app.json" file:

```
...
"exclude": [
    "test.ts",
    "**/*.spec.ts",
    "../**/*.spec.ts"
],
"include": [
    "**/*.ts",     <-- this line fixed the last problem
    "../src/**/*.ts"
]
...
```

**Comment by kevincam3** [comment]
Ok that fixed it. Great, it compiles with no problem. So the last thing is to explain how I get it to show my button html code that in the /src/app/game-control/game-control.component.html file?

**Comment by nording** [comment]
Okey good! Could you provide a screenshot of your test file for "/src/app/game-control/game-control.component.ts"? I would like to verify that the setup is correct.

**Comment by kevincam3** [comment]
Ok here it is:
![image](https://user-images.githubusercontent.com/870934/34221740-4c32aaee-e5a0-11e7-8dd1-aa12c6aab529.png)

**Comment by nording** [comment]
Allright, you have one test there, just add the following to the "it" function.

If you wan't a custom title that describe the example:
```
/** @uijarexample Custom title to example */             <-- this line is added
it("should create", () => {
expect(component).toBeTruthy();
})
```

Or if you don't want to add any title, just add this:
```
/** @uijarexample */          <-- this line is added
it("should create", () => {
expect(component).toBeTruthy();
})
```

**Comment by kevincam3** [comment]
Ok, this is great, we now have buttons, thanks a bunch for you help. Is there any way to get it to pull in the styling that's being applied to the button? Since this styling is part of the component and not global or external styling.

Here's what they look like when rendered from ng serve:

![image](https://user-images.githubusercontent.com/870934/34222137-af3ec72a-e5a1-11e7-9238-27d368c974b4.png)

Here's what they look like from UI-jar:
![image](https://user-images.githubusercontent.com/870934/34222207-edc0e438-e5a1-11e7-8268-f6ab09e4d124.png)

**Comment by nording** [comment]
It should load your styling as well (if you have a reference to it in your component), verify that there is not any cached result you get in the browser.

**Comment by kevincam3** [comment]
Ok, you're right, I just tested it. I forgot that it's using the global bootstrap css. This is great. Thanks a lot, I'll keep playing with it and any questions I'll reach out to you. Have a great day.

**Comment by nording** [comment]
Let me know if you have any questions!
