### ISSUE TITLE
Any way to have HTML view for components show dynamic values used to generate it? 

### ISSUE THREAD

**Issue by patcat** [ui-jar/ui-jar#11]
Been experimenting with ui-jar and was super happy to have gotten it to work! However, there's one thing that seems odd to me.

When clicking `< >`, we see the HTML for each component. However, if dynamic values are used, such as this in your sample app:

```
@Component({
  selector: 'x-card-test-host',
  template: `
    <x-card [padding]="padding">{{text}}</x-card>
  `
})
```

which when clicking the `< >` icon, shows:

```
<x-card [padding]="padding">{{text}}</x-card>
```

What would be better would be:

```
<x-card padding="true">Lorem ipsum dolor sit amet...</x-card>
```

Not sure if this might have an alternate solution from [#8](https://github.com/ui-jar/ui-jar/issues/8) but it seemed like something totally separate.

Thanks!

**Comment by nording** [comment]
Thanks for feedback!
The `<>` view is updated a bit according to #8, it will display component code together with template code in the next version. Then you will be able to see the bindings to each property :)

**Comment by nording** [comment]
Beta 12 is released, closing this as the feature is included in it.
