### ISSUE TITLE
Collaborate with Storybook

### ISSUE THREAD

**Issue by ndelangen** [ui-jar/ui-jar#12]
Hi @nording 

This project of yours looks amazing!
I'm a maintainer of storybook, which started support Angular recently. I'm wondering if you would be interested in working together?

**Comment by nording** [comment]
Hello @ndelangen 
Thanks! I would like to know more about it, what kind of collaboration do you have in mind? Do you have a specific idea?

**Comment by ndelangen** [comment]
@nording We have a few Angular experts and maintainers in the team. I'd love to add people to the team with Angular and style-guide experience.

Would you be interested in applying your expertise on storybook?

We're on a mission to make storybook a tool for everyone, no matter which framework users use, with loads of addons which can be used by all.

If you want to talk about it more, please join us on the [storybook slack](https://now-examples-slackin-rrirkqohko.now.sh/)

**Comment by nording** [comment]
Alright, at the moment I have a few other projects that I'm working on as well, so it might be hard to find the time for one more, but I will think about it. Appreciate that you ask me!
