### ISSUE TITLE
Hide private properties from API section

### ISSUE THREAD

**Issue by Karankang007** [ui-jar/ui-jar#13]
Thanks for creating this great library. Is their a way to exclude private component properties from the API documentation?

**Comment by nording** [comment]
Thanks! By default all private properties should be hidden in the API documentation.
It might be a bug if you see private properties in the API documentation, could you provide an example component where you see private properties in the documentation?

**Comment by nording** [comment]
@Karankang007 could you provide an example component to reproduce this?

**Comment by Karankang007** [comment]
```
/**
 * Primary button
 * @group Buttons
 * @component Test Button
 * @description Test Button Usage
 */
@Component({
  selector: 'test-button,
  templateUrl: './button.component.html',
  styleUrls: [
      './button.component.scss'
    ],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TestButtonComponent  {
  /**
   * Text to display in button
   */
  @Input()
  public text: string;
 
   /**
   * Font icon class for this button
   */
  @Input()
  public icon: string;

  /**
   * Static Button shape
   */
  private shape = 'square';

  /**
   * Add btn-icon class for icon buttons
   */
  @HostBinding('class.icon-btn')
  get btnClass() { return icon !== void 0; }
}
```

**Comment by nording** [comment]
Thanks for example! I have tried to reproduce it with that example but to me the only properties that is visible in the API-tab is the following:

* @Input() public text: string;
* @Input() public icon: string;
* @HostBinding('class.icon-btn') get btnClass()

Do you see the "private shape" property as well?

**Comment by Karankang007** [comment]
Right, in this case, i was not expecting the btnClass property to be available in the API-tab.

**Comment by nording** [comment]
Allright, if the property/method doesn't have a specified modifier, it is marked as public, therefore it is visible in the API-tab.

**Comment by nording** [comment]
@Karankang007 Are you satisfied with the answer? :) Is it ok to close?

**Comment by Karankang007** [comment]
Yes, @nording, this can be closed.
