### ISSUE TITLE
HostComponent in seperate file is not showing up in Example container

### ISSUE THREAD

**Issue by Karankang007** [ui-jar/ui-jar#16]
If the component referenced by @hostcomponent attribute is extracted out of the spec file, the example container no longer shows the code for it.

The host component still gets compiled and the output is shown in the DOM, but the actual code for the host component no longer shows up in the example container. This is what is shown instead:

```
@Component({
  selector: 'example-host',
  template: `<my-icon-button></my-icon-button>`
})
class ExampleHostComponent {
}
```

**Comment by nording** [comment]
I will take a look at this one!

**Comment by Karankang007** [comment]
This seems to be happening because only inline components get searched for example host component.
It should fallback to use the file path of the component in the import references at the top of the file to create the host component usage block.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Karankang007** [comment]
I will issue a pull request if time permits.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nording** [comment]
You are absolutely right! I have created a working solution with this locally, but it requires a bit of refactoring to make it more simple to maintain. I will make sure this get shipped in rc-1 (which I plan to release in the beginning of next week).

**Comment by Karankang007** [comment]
Great, thanks

**Comment by nording** [comment]
RC-1 is now released!

**Comment by Karankang007** [comment]
Thanks for the fix, this appears to be working now.
