### ISSUE TITLE
Set typescript dependency to ~2.3.0 instead of ^2.5.0 to match the angular supported ts version

### ISSUE THREAD

**Issue by kroeder** [ui-jar/ui-jar#2]
Angular 5 just recently started to officially support Typescript `2.4.0` but your package.json depends on`^2.5.x`

Angular 4 supported `"typescript": "~2.3.0"`

Shouldn't it be the same as the supported angular version?

**Comment by nording** [comment]
My bad :) I Will update that! Thanks!

**Comment by kroeder** [comment]
I did a PR https://github.com/kroeder/ui-jar/pull/1

**Comment by nording** [comment]
Beta-9 is released, closing this.

**Comment by kroeder** [comment]
I'm not sure why but your change does not work. My app had typescript ~2.4.2 as devDependencies and ui-jar caused npm install to install 2.6.x

I guess you have to define a range like this
`"typescript": ">=2.3.0 <2.4.2"`

2.4.2 is the latest 2.4.x version and the latest supported version by angular 5

**Comment by nording** [comment]
Allright, I have updated that, in the next release it will be available. Thanks!
Not sure why you get that typescript version, I tried the Angular CLI example, then I got version 2.3.4 of typescript.
I'm curious, do you use an package-lock.json file for your dependencies?
