### ISSUE TITLE
Minification Safety

### ISSUE THREAD

**Issue by Karankang007** [ui-jar/ui-jar#20]
The generated appData and its usage in getBootstrapComponent is not minification safe as it is trying to do lookup based on function name.

During minification the function names get shortened, and componentRefs property of appData no longer contain relevant infomration.

To test, use can use Angular CLI:
ng build --prod --aot=false

**Comment by nording** [comment]
Thanks! I will take a look at it :)

**Comment by nording** [comment]
A fix will be available in the next release v.1.1.0

**Comment by nording** [comment]
v1.1.0 is released!

**Comment by Karankang007** [comment]
Great, thanks for getting to this so quickly.

**Comment by nording** [comment]
Thanks a lot for your report! :)
