### ISSUE TITLE
Bundle weight of the app

### ISSUE THREAD

**Issue by zizizi17** [ui-jar/ui-jar#21]
Hello.
Will all the components created as the test components included to the main bundle of the application?
Won't it make it has bigger size?

**Comment by nording** [comment]
Hi @zizizi17!
You don't bundle UI-jar and your test components together with your main app.
UI-jar is a separated app from your main application.

Therefore UI-jar won't make your main app size bigger.

**Comment by zizizi17** [comment]
Correct if I am wrong, please. I create test components in my main application?

**Comment by nording** [comment]
Yes, you create your test components in your main application. But you should not bundle your test components in your main application. Only bundle the components you use in your main application.

**Comment by zizizi17** [comment]
Well done.
Thank you.
