### ISSUE TITLE
Enable the ability for documentation of the css classes as part of the ui-jar app

### ISSUE THREAD

**Issue by zizizi17** [ui-jar/ui-jar#27]
Hi. Can we discuss the next feature? 
Enable the ability for documentation of the css classes as part of the ui-jar app

**Comment by nording** [comment]
Hello,
Do you mean to view example of CSS-class usage? Like h1, h2 etc. stylings - on parts that is not an Angular component or directive?

**Comment by zizizi17** [comment]
Yes, exactly so

**Comment by nording** [comment]
It's possible to achieve that if you create a test host component that display the different kind of CSS examples you have. In next version (1.1.2 which I will release tomorrow) you also can use styleUrls in test host components. Then you only have to import your CSS to your test host component.

**Comment by nording** [comment]
v.1.1.2 is now available at npm.
