### ISSUE TITLE
HotReload does not work when the test code is changed

### ISSUE THREAD

**Issue by zizizi17** [ui-jar/ui-jar#28]
Hi. I faced the issue. 
HotReload does not work when the test code is changed.

**Comment by nording** [comment]
Hello,
Do you start it with the --watch flag?

**Comment by zizizi17** [comment]
Yes

**Comment by nording** [comment]
Allright, the script "start-ui-jar-example" from example project is not using the --watch flag.
I'm closing this - reopen if you see same issue when you use --watch flag.
