### ISSUE TITLE
Create the custom template for app

### ISSUE THREAD

**Issue by zizizi17** [ui-jar/ui-jar#29]
Is it possible to create the custom template for the main page of the application?

**Comment by nording** [comment]
Do you mean the start page? Or general theme?

**Comment by zizizi17** [comment]
Both of them

**Comment by nording** [comment]
It's possible to create custom CSS-theme, just replace the default one with yours.
The start page is currently not available to change with custom template - but sounds like a good idea!

**Comment by zizizi17** [comment]
Hi! Is there any update about this feature?

**Comment by nording** [comment]
Not at the moment, planned for later release!

**Comment by picheli20** [comment]
@zizizi17 you can update the colors after this PR: https://github.com/ui-jar/ui-jar/pull/55

For the home page we could use something like:

```html
<ui-jar-app>
  <!-- Home page content to be overwritten -->
</ui-jar-app>
```

What you think @nording ? I can take a look and update the `IntroductionComponent`

**Comment by nording** [comment]
@picheli20 that would be great! I'm doing some refactoring on other parts at the moment, but I guess it won't affect IntroductionComponent.

**Comment by nording** [comment]
@hughanderson4 Sounds like a good idea!
A workaround that works now if you just want to manage the title is to add following CSS:

```
ui-jar-app .app-title a {
    display: none;
}

ui-jar-app .app-title::before {
    content: 'My custom title';
    display: block;
}
```

**Comment by hughanderson4** [comment]
https://stackoverflow.com/a/49116319/213050

**Comment by picheli20** [comment]
@hughanderson4 nice! :) I'm adding as a config object, so it will be easier to add more fields.

**Comment by picheli20** [comment]
Unfortonetly it's not possible to pass the `ng-content` trough an bootstrap component :/ https://github.com/angular/angular/issues/4946, maybe for now i'll add on the config file as well and in the future we can refactor this part

**Comment by hughanderson4** [comment]
That's a real nice additional feature! Thanks for the great work.

I just want to say, what a fantastic concept, to use Unit Tests as the way to create UI-Jar examples.  Any time we can get extra value from writing unit tests, is a win-win.  Thanks for a great lib! 🍺
