### ISSUE TITLE
ng serve throws ERROR in UIjarModule is not an NgModule

### ISSUE THREAD

**Issue by kroeder** [ui-jar/ui-jar#3]
Starting ui-jar with ng serve for the first time throws `ERROR in UIjarModule is not an NgModule
`

After the first recompile (trigger --watch change detection) the error is gone - not sure what causes this (normally this happens with `npm link` in certain situations)

**Comment by nording** [comment]
I have seen that issue, sometimes it recompiles automatic when I get it. But I'm not getting it every time, just time to time.

Current workaround: Trigger a compile again, it works the second time.

**Comment by kroeder** [comment]
After being through endless trouble shooting with angular-cli I might figure out what's wrong... 

btw. for being fully CamelCase you might consider rename UIjarModule to UIJarModule 
https://angular.io/guide/styleguide#symbols-and-file-names 

It is a small breaking change but since this is .beta and not 1.0 release? Just seems cleaner to me - at the end of the day it's your choice :)

**Comment by nording** [comment]
I have figured out what's causing this error. Angular CLI uses Angular Compiler to compile files. The current UI-jar release (beta-8) is missing the required metadata.json files which include the metadata for the decorators it need. This is why the "ERROR in UIjarModule is not an NgModule" appears.

I will add the required metadata.json files in "beta-9"-release. That will fix this issue.

**Comment by nording** [comment]
Beta-9 is released, closing this.
