### ISSUE TITLE
Proper failure if failed to generate resources

### ISSUE THREAD

**Issue by Karankang007** [ui-jar/ui-jar#31]
**Versions**
UI-JAR: 1.1.2
NPM: 3.10.10

**Problem**
Currently if UI-JAR fails to generate resources, the NPM script execution continues to run. It should throw a proper exception or abort the node process if resource generate failed.

```
Generating resources...
Failed to generate resources.
```

**Comment by nording** [comment]
Thanks for the report! Does it work to generate with UI-jar v1.1.1? 

Could you make a temporary fix local in node_modules/ui-jar/src/init/init.js where the try catch with "Failed to generate resources." is logged? And show the error message so that I can check it out.

**Comment by Karankang007** [comment]
Hey @nording, i was able to reproduce this in previous versions as well.

I will post the actual error shortly.

**Comment by nording** [comment]
@Karankang007 Do you have the possibility to post your actual error? Then I can try to fix it!

**Comment by nording** [comment]
Release v.1.1.3 is available at npm.
