### ISSUE TITLE
The watcher does not appear to be working for spec files

### ISSUE THREAD

**Issue by thomasbottonari** [ui-jar/ui-jar#34]
The watcher appears to be working for me when I modify the component files themselves, but if I modify the ui-jar specfile it does not rebuild automatically.

**Comment by nording** [comment]
Could you provide your script config where you start with watcher enable?

**Comment by thomasbottonari** [comment]
These are the scripts I am using to launch ui-jar. I am not calling --watch, but I noticed if I added `--watch` to the `ui-jar` script, it just hangs saying 'Watching for file changes.' It never actually boots up.
```
"ui-jar": "node node_modules/ui-jar/dist/bin/cli.js --directory ./src/ --includes \\.ts$",
"start": "npm run ui-jar && ng serve ui-jar"
```
Below is an example of when I was adding `--watch`
```
"ui-jar": "node node_modules/ui-jar/dist/bin/cli.js --watch --directory ./src/ --includes \\.ts$",
"start": "npm run ui-jar && ng serve ui-jar"
```

**Comment by thomasbottonari** [comment]
I tried both of those methods, and while it says `Watching for file changes.` I haven't seen it rebuild when I save a spec file. Below are my two scripts, does something look incorrect to you?
```
"ui-jar": "node node_modules/ui-jar/dist/bin/cli.js --watch --directory ./src/ --includes \\.ts$",
"start": "concurrently \"npm run ui-jar\" \"ng serve ui-jar\""
```

**Comment by nording** [comment]
You are right! This is a bug, I found a way to repro it.
I have fixed it in master, I will try to release a fix on npm later this week.
Until next release a workaround is to do as follow where you define your test module setup:
```
/**
  * @uijar YourComponentRef
  */
const moduleDef = { imports: [ ... ], declarations: [ ... ] };
TestBed.configureTestingModule(moduleDef).compileComponents();
```

instead of:
```
/**
  * @uijar YourComponentRef
  */
TestBed.configureTestingModule({ imports: [ ... ], declarations: [ ... ] })
.compileComponents();
```

After next release, the later will work with --watch mode enabled as well.

**Comment by nording** [comment]
Release v1.1.4 is now available at npmjs!
