### ISSUE TITLE
Using of ngx-translate in the component

### ISSUE THREAD

**Issue by zizizi17** [ui-jar/ui-jar#38]
Hello. I need help with the injecting the ngx-translate module in the tests cases, so that I it results in the translated text(that is used in the component that i describe template) as the result?

**Comment by nording** [comment]
Could you provide your test setup for the specific case?

If you import ngx-translate module in your test module config it will be used with each example. Following link might help with test setup https://github.com/ngx-translate/example/blob/master/src/app/app.component.spec.ts ?

**Comment by zizizi17** [comment]
`
/**
         * @uijar TestComponent
         */
        TestBed.configureTestingModule({
            imports: [
                TranslateModule.forRoot({
                    loader: {
                        provide: TranslateLoader,
                        useFactory: (InitTranslateLoader),
                        deps: [HttpClient]
                    }
                })
            ],
            declarations: [TestComponent, TranslatePipe],
            providers: [TranslateService]
        })
            .compileComponents();
`

**Comment by nording** [comment]
Allright, I will try to repro it.

**Comment by zizizi17** [comment]
@nording Have you tried it?

**Comment by nording** [comment]
Could you provide full repro case?

**Comment by karthikRajDhandapani** [comment]
I have tried to include ngx-translate into the application, but in UI jar the below error is displayed
StaticInjectorError(UIJarModule)[MyService -> TranslateService]
Also attached screenshot with it
![translate_dependency_error](https://user-images.githubusercontent.com/44966146/48402732-5d182c80-e752-11e8-849b-03d600588142.png)


my-component.spec.ts

import {
    async,
    ComponentFixture,
    TestBed,
    TestModuleMetadata
  } from '@angular/core/testing';
import { MyComponent } from './my.component';
import { Component } from '@angular/core';
import { By } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { TranslateLoader, TranslateModule, TranslateService } from '@ngx-translate/core';
import { fromPromise } from 'rxjs/observable/fromPromise';
import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';
import { HttpClient } from '@angular/common/http';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import { TestService } from '../test.service';


export function HttpLoaderFactory(httpClient: HttpClient) {
    return new TranslateHttpLoader(httpClient);
}

const TRANSLATIONS_EN = require('../../locale/en.json');
const TRANSLATIONS_FR = require('../../locale/fr.json');

@Component({
  selector: 'my-test-host',
  template: `
	<my-component></my-component>
  `
})
class MyTestHostComponent {
    
}

describe('MyComponent', () => {
  let component: MyTestHostComponent;
  let fixture: ComponentFixture<MyTestHostComponent>;
  let translate: TranslateService;
  let http: HttpTestingController;

  beforeEach(async(() => {
    /**
     * @uijar MyComponent
     * @hostcomponent MyTestHostComponent
     */
    TestBed.configureTestingModule({
      imports: [TranslateModule.forRoot({
                    loader: {
                        provide: TranslateLoader,
                        useFactory: HttpLoaderFactory,
                        deps: [HttpClient]
                    }
                })
            ],
      declarations: [MyComponent, MyTestHostComponent],
      providers: [TranslateService, TestService]
    }).compileComponents();
    translate = TestBed.get(TranslateService);
    http = TestBed.get(HttpTestingController);
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(MyTestHostComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  /** @uijarexample My Component */
  it('should create', () => {
    spyOn(translate, 'getBrowserLang').and.returnValue('en');
    http.expectOne('/assets/i18n/en.json').flush(TRANSLATIONS_EN);
    http.expectNone('/assets/i18n/fr.json');

    // Finally, assert that there are no outstanding requests.
    http.verify();

    fixture.detectChanges();
    expect(MyTestHostComponent).toBeDefined();
  });
});


my.component.ts

import { Component } from '@angular/core';

@Component({
  selector: 'my-component',
  template: `<div><b>{{ "TEST"| translate }}</b></div>`,
  styles: []
})
export class MyComponent {

  constructor(private testService: TestService) {}
}

test.service.ts

import { Injectable, EventEmitter } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import 'rxjs/add/operator/map';

@Injectable()
export class TestService {

    constructor(public translate: TranslateService) {
        translate.addLangs(['en', 'fr']);
        translate.setDefaultLang('en');
        const browserLang = 'en';
        translate.use(browserLang.match(/en|fr/) ? browserLang : 'en');
    }
}

app.module.ts

export class WebpackTranslateLoader implements TranslateLoader {
  getTranslation(lang: string) {
    return fromPromise(import(`../locale/${lang}.json`));
  }
}

@NgModule({
  imports: [CommonModule,
            RouterModule,
            BrowserModule,
            TranslateModule.forRoot({
              loader: {
                  provide: TranslateLoader,
                  useClass: WebpackTranslateLoader,
                  deps: [HttpClient]
              }
            })],
  declarations: [MyComponent],
  exports: [MyComponent],
  providers: [TestService, TranslateService]
})
export class AppModule { }

locale/en.json

{
    "TEST": "Test locale works"
}

locale/fr.json

{
    "TEST": "Fr Test locale works"
}

Kindly let me know if i am missing something here

**Comment by nording** [comment]
I tried this example https://github.com/ngx-translate/example/blob/master/src/app/app.component.spec.ts and got it to work if I mocked the JSON-file with locale.

ngx-translate-example.component.ts
```
@Component({
selector: 'ngx-translate-example',
template: `
    {{ "title" | translate }}
`,
})
export class NgxTranslateExampleComponent implements OnInit {
  constructor(private translate: TranslateService) {}

  ngOnInit(): void {
    this.translate.setDefaultLang('sv');
  }

}
```

ngx-translate-example.component.spec.ts
```
import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import { NgxTranslateExampleComponent } from './ngx-translate.component';
import { TranslateLoader, TranslateModule, TranslateService } from "@ngx-translate/core";
import { HttpClient } from '@angular/common/http';
import { HttpClientTestingModule, HttpTestingController, TestRequest } from '@angular/common/http/testing';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';

export function HttpLoaderFactory(httpClient: HttpClient) {
  return new TranslateHttpLoader(httpClient);
}

describe('NgxTranslateExample', () => {
  let fixture: ComponentFixture<NgxTranslateExampleComponent>;

  beforeEach(async(() => {
    /** 
     * @uijar NgxTranslateExampleComponent  
     */
    TestBed.configureTestingModule({
      imports: [
        HttpClientTestingModule,
        TranslateModule.forRoot({
          loader: {
            provide: TranslateLoader,
            useFactory: HttpLoaderFactory,
            deps: [HttpClient]
          }
        })
      ],
      declarations: [
        NgxTranslateExampleComponent
      ],
      providers: [
        TranslateService
      ]
    }).compileComponents();
  }));


  /** @uijarexample Example ngx-translate */
  it('should translate title to correct locale', () => {
    fixture = TestBed.createComponent(NgxTranslateExampleComponent);
    const mockHttp = TestBed.get(HttpTestingController);
    const request: TestRequest = mockHttp.expectOne('/assets/i18n/sv.json');
    request.flush({
      "title": 'Min rubrik'
    });

    ...
  });
});
```

**Comment by picheli20** [comment]
I'm using the `ngx-translate` without any issue, you just need to import the `TranslateTestingModule` in your `imports`, like for example:
```
import { TranslateTestingModule } from 'ngx-translate-testing';
....
    /**
     * @uijar TicketCartComponent
     */
    TestBed.configureTestingModule({
      imports: [TranslateTestingModule.withTranslations({})],
      declarations: [TicketCartComponent],
    }).compileComponents();
```

**Comment by nording** [comment]
Thanks for example @picheli20 ! I'm closing this as it works with ngx-translate.
