### ISSUE TITLE
Slow navigation on page with large number of examples

### ISSUE THREAD

**Issue by Karankang007** [ui-jar/ui-jar#39]
I have a navigation group with 5 examples. 

When the user click on this navigation group, navigation is noticeably slower. Would it be possible to make the page rendering async? 

Like using a timeout perhaps to load the examples one after another to prevent blocking the navigation?

**Comment by nording** [comment]
A fix for this is available in master - it will be available via npm in the next release!

**Comment by nording** [comment]
A new release is available at npm (v1.1.5) with a fix for this issue.
