### ISSUE TITLE
Doing a fresh static build throws "Can't resolve '../../../temp/__ui-jar-temp'" error

### ISSUE THREAD

**Issue by thomasbottonari** [ui-jar/ui-jar#41]
I am attempting to build our ui-jar project so that I can host it internally for our dev team. However, doing a fresh build (`ng build && node node_modules/ui-jar/dist/bin/cli.js --directory ./src/ --includes \\.ts$`) gives the following error:

```
ERROR in ./node_modules/ui-jar/dist/src/app/app.module.js
Module not found: Error: Can't resolve '../../../temp/__ui-jar-temp' in '[MY-PROJECT-PATH]/node_modules/ui-jar/dist/src/app'
```

What I noticed is that the temp folder in question does not exist until you run the ui-jar application the first time. However, I am creating a static build, so I shouldn't have to do this.

**Comment by nording** [comment]
Try to switch order of the scripts, like this:
```bash
node node_modules/ui-jar/dist/bin/cli.js --directory ./src/ --includes \\.ts$ && ng build
```
Does it works then?

**Comment by thomasbottonari** [comment]
Thanks, that did the trick!
