### ISSUE TITLE
Running ui-jar in an NX setup

### ISSUE THREAD

**Issue by paesku** [ui-jar/ui-jar#43]
@nording I like your approach running this tool within a test environment.
I tried to run it within an [NX](https://nrwl.io/nx) setup which has a slightly different structure than pure Angular CLI projects.

```bash
├── README.md
├── angular.json
├── apps
│   ├── app1
│   │   ├── browserslist
│   │   ├── src
│   │   ├── tsconfig.app.json
│   │   └── tslint.json
│   └── ui-jar
│       ├── browserslist
│       ├── src
│       │   ├── app
│       │   │   ├── app.component.html
│       │   │   ├── app.component.scss
│       │   │   ├── app.component.ts
│       │   │   └── app.module.ts
│       │   ├── assets
│       │   ├── environments
│       │   │   ├── environment.prod.ts
│       │   │   └── environment.ts
│       │   ├── favicon.ico
│       │   ├── index.html
│       │   ├── main.ts
│       │   ├── polyfills.ts
│       │   ├── styles.scss
│       │   └── test.ts
│       ├── tsconfig.app.json
│       └── tslint.json
├── jest-global-mocks.ts
├── jest.config.js
├── libs
│   ├── lib1
│   │   ├── src
│   │   └── tsconfig.lib.json
│   └── lib2
│       ├── src
│       │   ├── xyz
│       │   │   ├── xyz.component.spec.ts
│       │   │   ├── xyz.component.ts
│       │   └── ute.module.ts
│       └── tsconfig.lib.json
├── nx.json
├── package-lock.json
├── package.json
├── setup-jest.ts
├── tools
├── tsconfig.json
├── tsconfig.spec.json
└── tslint.json
```
 
As a testing framework I'm using [jest](https://jestjs.io/).
To me it's not exactly clear, wherefore the exclude/include setup is and how it can match the expectations  within my setup.

Open "projects/ui-jar/tsonfig.app.json" and add following:

```bash
"exclude": [
    ...
    "../../src/**/*.spec.ts"
]
"include": [
    "**/*.ts",
    "../../src/**/*.ts"
]
```

Appreciate your work and feedback.

**Comment by nording** [comment]
@paesku the exclude/include setup is to make sure your build tool include/exclude your real source files and not only search for them inside your "ui-jar" app folder. 
Does this setup work for you?

```
"exclude": [
    ...
    "../app1/**/*.spec.ts"
]
"include": [
    "**/*.ts",
    "../app1/**/*.ts"
]``

**Comment by paesku** [comment]
@nording since I want to have components from my **`lib2`** rendered, I reference them like this:

```json
"exclude": [
    "src/test.ts",
    "**/*.spec.ts",
    "../../libs/lib2/**/*.spec.ts"
  ],
  "include": [
    "**/*.ts",
    "../../libs/lib2/**/*.ts"
  ]
```

**Comment by nording** [comment]
@paesku allright, do you get any error message when building?

**Comment by paesku** [comment]
Unfortunately not. It's building straight away and the UI is showing up.
Any recommendations for where to start digging?

nording <notifications@github.com> schrieb am Do., 6. Sep. 2018, 17:00:

**Comment by nording** [comment]
It sounds like you are missing some "ui-jar" comments in your code. Do you have this in your code?
https://github.com/ui-jar/ui-jar/blob/master/README.md#example-usage-basic

**Comment by paesku** [comment]
Yes comments in the component class as well in the spec file are there. 

package.json:
```
json
    "ui-jar": "node node_modules/ui-jar/dist/bin/cli.js --directory ./libs/lib2/src/ --includes \\.ts$",
    "ui-jar:serve": "npm run ui-jar && ng serve ui-jar",
```

**Comment by picomis** [comment]
I use nx and generated the docs app with this tsconfig.app.json:
```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc/apps/docs",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts",
    "../../libs/**/*.spec.ts"
  ],
  "include": [
    "**/*.ts",
    "../../libs/**/*.ts"
  ]
}
```

NPM scrips:
```
"ui-jar": "node node_modules/ui-jar/dist/bin/cli.js --directory ./libs/ --includes \\.ts$",
 "docs:watch": "npm run ui-jar -- --watch",
 "docs:serve": "npm run ui-jar && ng serve docs"
```

Works as expected.

**Comment by paesku** [comment]
@picomis thank you pointing me in the right direction.  
First I referenced my app's path for ui-jar instead the `./libs/` path. 
Second I missed the comment in my component to group it within the sidebar:  

``` typescript
/**
 * @group Layout
 * @component LabelValue
 * @description Lorem ipsum dolor sit amet, consectetur adipiscing elit.
 */
```

Thanks all for help.
