### ISSUE TITLE
Issue with build? (Angular 7)

### ISSUE THREAD

**Issue by Maks-Yaremenko** [ui-jar/ui-jar#53]
After all steps of installation and run application I have an empty ui-jar app on :4200 port. (No components there). 
I added required comments: @group, @component inside component, and its spec file.
Run script again.. but nothing changes.
I tested multiple versions of ui-jar and find out that only combination:
```
Angular 6 & ui-jar 1.1.6 & typescript 2.7.2 works OK
```
I tried different ways to configure with --config and without... this is my package.json
```
{
  "name": "ui-jar-application",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "ui-jar": "node node_modules/ui-jar/dist/bin/cli.js --directory ./src/app/ --includes \\.ts$",
    "start-ui-jar-example": "npm run ui-jar && ng serve ui-jar"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.0.0",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "@types/mocha": "^5.2.5",
    "core-js": "^2.5.4",
    "i": "^0.3.6",
    "rxjs": "~6.3.3",
    "ui-jar": "^1.1.7",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "~7.0.6",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/language-service": "~7.0.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
}
```

tsconfig.app.json
```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/app",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts",
    "../../src/**/*.spec.ts"
  ],
  "include": [
    "**/*.ts",
    "../../src/**/*.ts"
  ]
}
```
pic: http://joxi.ru/823dyDgcJkWvLA

```
ERROR in projects/ui-jar/src/app/app.component.spec.ts(4,1): error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.
projects/ui-jar/src/app/app.component.spec.ts(5,3): error TS2304: Cannot find name 'beforeEach'.
projects/ui-jar/src/app/app.component.spec.ts(13,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.
projects/ui-jar/src/app/app.component.spec.ts(16,5): error TS2304: Cannot find name 'expect'.
projects/ui-jar/src/app/app.component.spec.ts(19,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.
projects/ui-jar/src/app/app.component.spec.ts(22,5): error TS2304: Cannot find name 'expect'.
projects/ui-jar/src/app/app.component.spec.ts(25,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.
projects/ui-jar/src/app/app.component.spec.ts(29,5): error TS2304: Cannot find name 'expect'.

i ｢wdm｣: Failed to compile.
```

Please let me know if smth additional is required. thx

**Comment by nording** [comment]
Make sure that you have all types you need.
Add this till tour tsconfig.app.json:
```
"typeRoots": [
            "node_modules/@types"
]```

**Comment by nording** [comment]
Check that you import needed modules in your test, the error you describe sounds like a missing module in "configureTestingModule" setup.

**Comment by CinnamonRage** [comment]
> sorry, it was the issue with exclude. But now I have another issue. I am trying to get the demo of the component that uses angular-material, my app using standard way (ng serve) works ok and component display OK, but I got the error in the browser when I am trying to show this component in ui-jar.

What was the issue with the exclude? I am having similar issues, I get an empty UI-jar site with no found components.

**Comment by Maks-Yaremenko** [comment]
Afaik it was related to ui-jar app config... i gave up go use it so... i dont remember all details...

**Comment by vigneshikl** [comment]
> sorry, it was the issue with exclude. But now I have another issue. I am trying to get the demo of the component that uses angular-material, my app using standard way (ng serve) works ok and component display OK, but I got the error in the browser when I am trying to show this component in ui-jar.
> 
> ```
> core.js:12501 ERROR Error: Template parse errors:
> 'mat-progress-bar' is not a known element:
> 1. If 'mat-progress-bar' is an Angular component, then verify that it is part of this module.
> 2. If 'mat-progress-bar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<mat-progress-bar mode="indeterminate">
> 
> </mat-progress-bar>
> "): ng:///TempModule623d8e62e21a217c5f4b34ec525d0da3/ClockComponent.html@0:0
>     at syntaxError (compiler.js:2547)
>     at TemplateParser.push.../../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:19495)
>     at JitCompiler.push.../../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:25041)
>     at JitCompiler.push.../../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:25028)
>     at compiler.js:24971
>     at Set.forEach (<anonymous>)
>     at JitCompiler.push.../../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:24971)
>     at compiler.js:24881
>     at Object.then (compiler.js:2538)
>     at JitCompiler.push.../../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:24880)
> ```
> does it has some specific way to import modules?...
> I tried to import material modules in ui-jar/app.module... but no success


Is this Issue resolved ? I have the same Issue!  @Maks-Yaremenko

**Comment by nording** [comment]
@vigneshikl could you include an example with a repro?

**Comment by vigneshikl** [comment]
@nording  I have pushed the sample code into git. please have a look. I am just using mat-card component.It  throws the error.
![UI-JAR-AngularMatIssue](https://user-images.githubusercontent.com/14275355/55702442-3950ce00-59f4-11e9-8dac-2f6b5b97b482.png)


**Code:**
[https://github.com/vigneshikl/example-app-with-angular-cli](url)

**Comment by nording** [comment]
@vigneshikl thanks! It look like you is missing to import "MatCardModule" In your test setup:

 `TestBed.configureTestingModule({
      declarations: [ CardComponent, MyTestComponent ]
    }).compileComponents();`

Make sure to import it like this:

 `TestBed.configureTestingModule({
      imports: [MatCardModule],
      declarations: [ CardComponent, MyTestComponent ]
    }).compileComponents();`

Does it solve your issue?

**Comment by vigneshikl** [comment]
Ya..I have added that too. But not fixing..(In the shared code i missed to include that)

**Comment by vigneshikl** [comment]
You are rite @nording ! it is working fine.Thanks a lot!!!
