### ISSUE TITLE
Services, Pipes, Directives...

### ISSUE THREAD

**Issue by thotty** [ui-jar/ui-jar#57]
Has any plan to include `services`, `directives` and `pipes` like the `components`?

**Comment by nording** [comment]
Directive, pipes and services are working if you have tests that include a test host.

**Comment by nording** [comment]
Check this example with test host - https://github.com/ui-jar/ui-jar/blob/master/README.md#example-usage-with-test-host-component

This within your service file:
```
/**
 * @group My group
 * @component Service Name in meny
 */
@Injectable()
export class TestService {
    /** Doc about myProperty */
    myProperty: boolean = true;
    ...
}

**Comment by thotty** [comment]
I tried this..
My service not show in API documentation, but it's probably that I done some mistake..
I'll try again..

Thanks

**Comment by picheli20** [comment]
@thotty did you managed? :) Maybe you are missing something on the spec files

**Comment by thotty** [comment]
> @thotty did you managed? :) Maybe you are missing something on the spec files

Hi, yeah... I managed!
I had to change my focus to other project.. But any way, thanks.
