### ISSUE TITLE
Scss imports not supported

### ISSUE THREAD

**Issue by GeorgeTailorZooPlus** [ui-jar/ui-jar#61]
I have a couple of files with some scss, which I import in some of my components.
The configuration in angular.json is as follows:
```
            "styles": [
              "src/styles.scss",
              "src/styles/_variables.scss"
            ],
```

While in my component I have something like this: 

`@import "variables";`

When I try to run `npm run start-ui-jar-example` I get the following messages:
``` 
Generating resources...
Generated resources successfully.

...


@import "variables";
^
      File to import not found or unreadable: variables.
```
And the process exists without starting the app.

Standard `ng serve` or `ng build` works fine.

**Comment by GeorgeTailorZooPlus** [comment]
Sure.
https://github.com/GeorgeTailorZooPlus/ui-jar-angular-scss

**Comment by GeorgeTailorZooPlus** [comment]
Sorry, I've added a couple of small fixes here and there.
I suspect that ui-jar ignores the following rule of schematics:
```
			"stylePreprocessorOptions": {
				"includePaths": [
				  "src/styles"
				]
			}
```

**Comment by GeorgeTailorZooPlus** [comment]
Actually adding this option to `ui-jar` config in `angular.json` fixed the issue. Sorry, my bad.

**Comment by nording** [comment]
Great that you solved it!

**Comment by luardo** [comment]
Hi, I see that the issue is closed. But I am having the same issue. Adding the stylePreprocessorOptions hasn't fix the problem yet.  
I added the stylePreprocessorOptions property, but it still showing the same error to me. 
Did you find more details about this issue?
