### ISSUE TITLE
Add possibility to use "templateUrl" in a test host component

### ISSUE THREAD

**Issue by nording** [ui-jar/ui-jar#7]
At the moment, you can only show a test host component that uses an inline template.
Add possibility to use a test host component that uses a relative "templateUrl".

**Comment by Karankang007** [comment]
This works without any changes if the host component is moved to a separate file.

**Comment by nording** [comment]
Yepp thats right! The solution is to make sure both inline and in separate file works :)

**Comment by nording** [comment]
RC-1 is now released!
